# NumPy Basics Notebook

## What is NumPy?
NumPy (Numerical Python) is a Python library for numerical computing.

- Fast array operations
- Mathematical functions
- Matrix operations
- Used in Data Science and Machine Learning

In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.ndim

1

In [5]:
arr2.shape

(2, 3)

In [6]:
arr2.size

6

In [7]:
arr.dtype

dtype('int64')

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
a=np.arange(1,13)
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr[2]

np.int64(30)

In [ ]:
arr[1:4]

In [14]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

In [15]:
x-y

array([-3, -3, -3])

In [16]:
x*y

array([ 4, 10, 18])

In [17]:
y/x

array([4. , 2.5, 2. ])

In [18]:
np.sqrt(np.array([4,9,16]))

array([2., 3., 4.])

In [19]:
arr.max()

np.int64(40)

In [20]:
arr.min()

np.int64(10)

In [21]:
arr.mean()

np.float64(25.0)

In [22]:
arr.sum()

np.int64(100)

In [23]:
c=np.array([5,2,9,1])
np.sort(c)

array([1, 2, 5, 9])

In [24]:
np.unique(np.array([1,2,2,3,3,4]))

array([1, 2, 3, 4])

In [25]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Cheat Sheet

- np.array()
- np.zeros()
- np.ones()
- np.arange()
- np.linspace()
- reshape()
- shape
- size
- ndim
- dtype
- max()
- min()
- mean()
- sum()
- np.sort()
- np.unique()
- .T